---
title: "semmst_stimuli"
author: "Alex Ilyés"
date: '2022 01 07 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(readxl)
library(tidyr)
library(scales)
library(ggplot2)
library(psycho)
library(ggpubr)
library(rstatix)
```

# STIMULI

## Descriptives about the cosine similarities 

```{r}

stimuli <- read_excel("ingeranyag/stimuli_v1.1_nophon_excel.xlsx")

stimuli %>%
  group_by(stim_type) %>%
  get_summary_stats(cosine_metric, type = "mean_sd")

stimuli_datapoints = stimuli %>%
  filter(stim_type == "DISTANT" | stim_type == "CLOSE") %>%
  group_by(stim_type)

stimuli %>%
  filter(stim_type == "DISTANT" | stim_type == "CLOSE") %>%
  group_by(stim_type) %>%
  summarize(
    mean_cos = mean(cosine_metric, na.rm = TRUE),
    sd_cos = sd(cosine_metric, na.rm = TRUE)
    ) %>%
  ggplot(aes(x=stim_type, y=mean_cos, fill=stim_type)) +
    geom_bar(stat="identity", width = 0.4) +
    #geom_errorbar(aes(ymin=mean_cos-sd_cos, ymax=mean_cos+sd_cos), width=.2,
    #             position=position_dodge(.9), size=0.86) +
    geom_point(data=stimuli_datapoints, aes(x=stim_type, y=cosine_metric, fill=stim_type), position = position_dodge(width=1)) +
    scale_fill_manual(values=c("royalblue2","gold2")) +
    coord_cartesian(ylim=c(0.4,0.9)) +
    theme_minimal() +
    theme(legend.position = "none") +
    labs(x = "Type of stimulus", y = "Mean of cosine similarity ", title = "Mean cosine similarities of different lures to the target") +
    theme(text = element_text(size = 26))
  
  
```

## Full stimlist
```{r}
se <- function(x){sd(x)/sqrt(length(x))}

stimuli_full <- read_excel("../ingeranyag/stimuli_v1.3.xlsx")

stimuli_full_nogyak = stimuli_full %>%
  filter(stim_type != "GYAK_ENC") %>%
  filter(stim_type != "GYAK_REC") 

```

## Noun frequency

```{r}
stimuli_full %>%
  group_by(stim_type) %>%
  get_summary_stats(noun_freq, type = "mean_sd")

stimuli_full_nogyak %>%
  select(stim_type, noun_freq) %>%
  group_by(stim_type) %>%
  summarise(my_mean = mean(noun_freq), my_se = se(noun_freq)) %>%
  ggplot(aes(factor(stim_type, levels=c("TARG", "CLOSE", "DISTANT", "FOIL")))) +
    geom_bar(aes(y=my_mean), stat="identity") +
    geom_errorbar(aes(y=my_mean, ymin = my_mean - my_se, ymax = my_mean + my_se), stat="identity") +
    geom_point(data = stimuli_full_nogyak, aes(y=noun_freq), stat='identity', position = position_dodge2(width=1, preserve ="single")) +
    labs(x = "Type of stimulus", y = "Noun frequency", title = "Noun frequency by stimulus type")


means_stimuli_full = stimuli_full_nogyak %>%
    select(stim_type, noun_freq, noun_char, noun_syll, noun_phon, adj_freq, adj_char, adj_syll, adj_phon) %>%
    group_by(stim_type) %>%
    summarise_all(tibble::lst(mean,se)) %>% 
    gather(key, value, -stim_type) %>%
    arrange(stim_type, sub('_.*', '', key), sub('.*_', '', key)) %>%
    separate(key, into = c('type', 'var', 'metric'), '_') %>%
    spread(metric, value)

means_stimuli_adj = means_stimuli_full %>%
  filter(type == "adj") 

means_stimuli_noun = means_stimuli_full %>%
  filter(type == "noun") 

```

##Covariates different for adjectives and nouns

```{r}
stimuli_full_nogyak %>%
    select(stim_type, noun_freq, noun_char, noun_syll, noun_phon, adj_freq, adj_char, adj_syll, adj_phon) %>%
    group_by(stim_type) %>%
    gather(key, value, -stim_type) %>%
    arrange(stim_type, sub('_.*', '', key), sub('.*_', '', key)) %>%
    separate(key, into = c('type', 'var'), '_') %>%
    filter(type == "adj") %>%
    ggplot(aes(factor(stim_type, levels=c("TARG", "CLOSE", "DISTANT", "FOIL")), fill = stim_type)) +
      geom_bar(data= means_stimuli_adj,aes(y=mean), stat="identity") +
      geom_errorbar(data= means_stimuli_adj, aes(y=mean, ymin = mean - se, ymax = mean + se, stat="identity")) +
      geom_point(aes(y=value), stat='identity', position = position_dodge2(width=1, preserve ="single")) +
      labs(x = "Type of stimulus", y = "Measures", title = "Covariates by stimulus type for adjectives") +
      theme(legend.position = "none") +
      #facet_wrap(~var, scales = "free")
      facet_wrap(~var, scales = "free")

stimuli_full_nogyak %>%
    select(stim_type, noun_freq, noun_char, noun_syll, noun_phon, adj_freq, adj_char, adj_syll, adj_phon) %>%
    group_by(stim_type) %>%
    gather(key, value, -stim_type) %>%
    arrange(stim_type, sub('_.*', '', key), sub('.*_', '', key)) %>%
    separate(key, into = c('type', 'var'), '_') %>%
    filter(type == "noun") %>%
    ggplot(aes(factor(stim_type, levels=c("TARG", "CLOSE", "DISTANT", "FOIL")), fill = stim_type)) +
      geom_bar(data= means_stimuli_noun,aes(y=mean), stat="identity") +
      geom_errorbar(data= means_stimuli_noun, aes(y=mean, ymin = mean - se, ymax = mean + se, stat="identity")) +
      geom_point(aes(y=value), stat='identity', position = position_dodge2(width=1, preserve ="single")) +
      labs(x = "Type of stimulus", y = "Measures", title = "Covariates by stimulus type for nouns") +
      theme(legend.position = "none") +
      #facet_wrap(~var, scales = "free")
      facet_wrap(~var, scales = "free")
```
##Covariates for word pairs

```{r}
means_stimuli_wpcov = stimuli_full_nogyak %>%
    select(stim_type, ya_ert_mean, ya_konk_mean, ya_aro_mean) %>%
    group_by(stim_type) %>%
    summarise_all(tibble::lst(mean,se)) %>% 
    gather(key, value, -stim_type) %>%
    arrange(stim_type, sub('_.*', '', key), sub('.*_', '', key)) %>%
    separate(key, into = c('agegroup', 'var', 'var2', 'metric'), '_') %>%
    spread(metric, value) %>%
    mutate(var = recode(var, aro = "arousal", ert = "meaningfulness", konk = "concreteness"))

stimuli_full_nogyak %>%
  select(itemno, stim_type, ya_ert_mean, ya_konk_mean, ya_aro_mean, ya_ert_sd, ya_konk_sd, ya_aro_sd) %>%
  group_by(itemno, stim_type) %>%
  gather(key, value, -c(itemno, stim_type)) %>%
  arrange(itemno, stim_type, sub('_.*', '', key), sub('.*_', '', key)) %>%
  separate(key, into = c('agegroup', 'var', 'metric'), '_') %>%
  filter(metric == "mean") %>%
  mutate(var = recode(var, aro = "arousal", ert = "meaningfulness", konk = "concreteness")) %>%
  ggplot(aes(factor(stim_type, levels=c("TARG", "CLOSE", "DISTANT", "FOIL")), fill = stim_type)) +
      geom_bar(data= means_stimuli_wpcov,aes(y=mean), stat="identity") +
      geom_errorbar(data= means_stimuli_wpcov, aes(y=mean, ymin = mean - se, ymax = mean + se, stat="identity")) +
      geom_point(aes(y=value), stat='identity', position = position_dodge2(width=1, preserve ="single")) +
      labs(x = "Type of stimulus", y = "Measures", title = "Questionnaire covariates by stimulus type") +
      coord_cartesian(ylim= c(1,7)) +
      theme(legend.position = "none") +
      #facet_wrap(~var, scales = "free")
      facet_wrap(~var, scales = "free")
  

```
```{r}

stimuli_full_nogyak %>%
  filter(stim_type != "TARG") %>%
  filter(stim_type != "FOIL") %>%
  ggplot(aes(x = cosine_metric, y = ya_ert_mean)) +
    geom_point() +
    geom_smooth(method = "lm") +
    xlab("cosine similarity") + ylab("meaningfulness") +
    ggtitle("Meaningfulness and the cosine similarity of lures to target")
    

stimulis_csak_closedist = stimuli_full_nogyak %>%
  filter(stim_type != "TARG") %>%
  filter(stim_type != "FOIL")

cor.test(stimulis_csak_closedist$cosine_metric, stimulis_csak_closedist$ya_ert_mean)

```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.




